export const Action = {
  CHANGE_CITY: 'CHANGE_CITY',
  FILL_OFFER_LIST: 'FILL_OFFER_LIST',
  CHOOSE_SORTING_OPTIONS: 'CHOOSE_SORTING_OPTIONS',
  LOAD_OFFER_LIST: 'LOAD_OFFER_LIST',
  CHANGE_STATUS_LOAD_OFFER_LIST: 'CHANGE_STATUS_LOAD_OFFER_LIST',
  CHANGE_STATUS_AUTHORIZATION: 'CHANGE_STATUS_AUTHORIZATION',
  REDIRECT: 'REDIRECT',
  SET_USER_EMAIL: 'SET_USER_EMAIL',
  SET_USER_PASSWORD: 'SET_USER_PASSWORD'
};
